# Generated by Django 3.0 on 2019-12-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_flor_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flor',
            name='imagen',
            field=models.ImageField(null=True, upload_to='flores'),
        ),
    ]
